# Generated by Django 5.2.6 on 2025-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car Name', max_length=255)),
                ('brand', models.CharField(help_text='Car Brand', max_length=100)),
                ('release_date', models.DateField(help_text='Release Date')),
                ('car_type', models.CharField(help_text='Car Type (e.g., SUV, Sedan)', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Car Price (e.g., 1500000.00)', max_digits=10)),
                ('horsepower', models.IntegerField(help_text='Horsepower (e.g., 250)')),
            ],
        ),
    ]
